
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Model Registry API - Phase 2

Globals:
  Function:
    Runtime: python3.11
    Timeout: 30
    MemorySize: 512

Resources:
  ModelRegistryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: model-registry
      CodeUri: .
      Handler: src.api.main.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
